### ISSUE TITLE
Adding translations

### ISSUE THREAD

**Issue by theBest3000** [Aarontheissueguy/WaterCount#5]
Would be nice if we could translate the texts in the app to different languages.

**Comment by Vistaus** [comment]
I support this request and will provide the Dutch translation once translation is possible 🙂

**Comment by Aarontheissueguy** [comment]
Cool! I'll get back to you Asap.

**Comment by ghost** [comment]
And I would be pleased to help for French translations! Maybe #7 is a good starting point?

**Comment by Aarontheissueguy** [comment]
Basic support for translation is given now but in my testing with german I couldnt get it to work properly for some reason. The name changes without any problems but the strings in the Main.qml file dont. I looked at some other Apps but couldnt find the problem. If someone knows the problem I'd be quite happy.

**Comment by Aarontheissueguy** [comment]
Ok everything works now. I found the Issue. If you want to you can start translating now. I recommend using poedit. Here is the official UbPorts guide: https://docs.ubports.com/en/latest/contribute/translations.html

**Comment by theBest3000** [comment]
What was the issue? Couldn't figure it out...

**Comment by Aarontheissueguy** [comment]
dependencies and conflicting librarys. I found a Solution by using the Ubuntu.Components api.

**Comment by Aarontheissueguy** [comment]
> And I would be pleased to help for French translations! Maybe #7 is a good starting point?

Hey, I finally found time to compile everything with the new translations and there seems to be an issue with the french one, which causes an error with cmake. I have no idea what causes this error. If you know what is going on pls let me know.
